### ISSUE TITLE
Mark as deprecated or change ownership

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/security-vocab#10]
This repo should be moved to a new home or marked as archived or deprecated. 

See: https://github.com/w3c-ccg/community/issues/97

**Comment by msporny** [comment]
> marked as archived or deprecated.

No, -1, please don't do this.

/cc @mattcollier @dlongley @davidlehn -- help

**Comment by msporny** [comment]
@mattcollier @dlongley @davidlehn did you guys have some sort of conversation with @OR13 where everyone decided to deprecate/archive the Security Vocabulary and JSON-LD Context?

**Comment by davidlehn** [comment]
I'm not sure what's going on.  Maybe just suggesting a move to digitalbazaar vs w3c-dvcg.
See also: https://github.com/digitalbazaar/jsonld-signatures/issues/82

**Comment by OR13** [comment]
I'd be happy with move to ccg or to digitalbazaar.

AFAIK its just an issue of hitting transfer on the repo.

**Comment by davidlehn** [comment]
Yes, it's not hard to hit the buttons.  I think the confusion is why this request is being made in the first place.  Moving a repo won't really change anything except the URL.  What's wrong with keeping the work here?

**Comment by OR13** [comment]
https://github.com/w3c-ccg/community/issues/97#issue-521700716

This WG is getting closed/archived. It hurts the reputation of any project that uses this npm module as a dependency to have the source live in an closed/archived github organization... and it hurts the perception of jsonld to have this issue get raised on ccg calls so regularly.

Likewise, it will help us get additional collaborators / build confidence around the use of jsonld signatures to simply move the repo to an active wg.

We (Transmute) rely on this npm module, we want to make sure its in a github organization that is active.

**Comment by davidlehn** [comment]
w3c-dvcg is a CG not a WG.  Can you reference details about when and why this group would be closed and/or archived?  Or are you saying just this particular repo?  I don't understand why we would go to the trouble to move all of the w3c-dvcg repos elsewhere.  That seems like busy work for no or little gain.  Is there a reason people don't want to contribute here?  Clearly some miscommunication going on.

**Comment by jandrieu** [comment]
@davidlehn The chairs of the CCG have been keeping the DVCG going for several years now with little progress to show for it. After discussing the options--and noting our failure to recruit additional cryptographers and others willing to do the work to move DVCG work items forward--we announced to the CCG and DVCG that all DVCG work will either be archived or moved to a more active home, such as the CCG.

Of course, if you're volunteering to chair the DVCG moving forward, we could potentially arrange an election instead of shutting down the group. However, since we have announced the plans to shut down the DVCG, you are literally the first person who questioned that intention. Maybe others are also perplexed, so your question is legitimate. 

If *ANYONE* wants to step up and take over the DVCG, that's something we should consider.

**Comment by msporny** [comment]
> If ANYONE wants to step up and take over the DVCG, that's something we should consider.

No, we should shut down the DVCG, save what we can into the CCG, and move on as we discussed in the CCG.

What I was objecting to was archiving/deprecating an actively developed and used vocabulary (this repository). 

Now that W3C-CCG owns this repo, I think this issue is resolved, and am closing it.
